apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "farm-system.fullname" . }}-backend
  labels:
    {{- include "farm-system.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "farm-system.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "farm-system.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "farm-system.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.backend.targetPort }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "farm-system.fullname" . }}-secrets
                  key: mongodb-uri
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "farm-system.fullname" . }}-secrets
                  key: redis-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "farm-system.fullname" . }}-secrets
                  key: jwt-secret
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "farm-system.fullname" . }}-secrets
                  key: jwt-refresh-secret
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "farm-system.fullname" . }}-secrets
                  key: session-secret
            - name: JWT_EXPIRES_IN
              value: {{ .Values.env.JWT_EXPIRES_IN | quote }}
            - name: JWT_REFRESH_EXPIRES_IN
              value: {{ .Values.env.JWT_REFRESH_EXPIRES_IN | quote }}
            - name: RATE_LIMIT_WINDOW
              value: {{ .Values.env.RATE_LIMIT_WINDOW | quote }}
            - name: RATE_LIMIT_MAX
              value: {{ .Values.env.RATE_LIMIT_MAX | quote }}
            - name: HEALTH_CHECK_INTERVAL
              value: {{ .Values.env.HEALTH_CHECK_INTERVAL | quote }}
            - name: METRICS_ENABLED
              value: {{ .Values.env.METRICS_ENABLED | quote }}
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            {{- toYaml .Values.healthcheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.healthcheck.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: uploads
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "farm-system.fullname" . }}-uploads
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: logs
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "farm-system.fullname" . }}-logs
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
